Aded ideogram for ``GENOME`` mode
nf-core/genomeqc pull request #102
Opened 2024-12-06 10:00 UTC by FernandoDuarteF

Close #98.

## Changes

1. Added `plot_makers1.R` and adapted `genome_ideogram.nf` from the BUSCO [support protocol 2](https://gitlab.com/ezlab/busco_protocol/-/tree/main/support_protocol2/).
2. Changed version of BUSCO in `busco/busco/main.nf` module to v5.8.0 (see #97).

## Comments

Probably some code cleaning is necessary before merging, specially regarding the **R scripts**. Other than that, this is working as expected, at least on the test dataset.

2024-12-06 12:01 UTC, FernandoDuarteF commented
Perhaps it would be a good idea to have a single module for the BUSCO ideogram, as now there is one for genome only mode (renamed to `genome_only_busco_ideogram.nf`) and one for genome and annotation (renamed to `genome_annotation_busco_ideogram.nf`).

We shoould also rename some scripts in the `/bin` folder to make them more descriptive. I'll deal with this later.

2024-12-06 14:42 UTC, chriswyatt1 commented
We could just add this to another issue for now. Yes, would make sense to have in once module, but I think this way is fine for now

2024-12-06 14:44 UTC, chriswyatt1 commented on modules/local/genome_only_busco_ideogram.nf
We should not have this: `$projectDir/bin/plot_busco_ideogram.R`

Just make sure the shebang is correct in the R code

2024-12-06 14:46 UTC, chriswyatt1 commented on subworkflows/local/genome_and_annotation.nf
Remove all the blanked out comments that we don't need:

`//removed this temporarily:, ch_karyotype`

2024-12-06 14:47 UTC, chriswyatt1 requested changes
Just a few little things to change, commented later

2024-12-09 12:16 UTC, FernandoDuarteF commented on modules/local/genome_only_busco_ideogram.nf
Yep, I forgot to change this

2024-12-09 18:02 UTC, FernandoDuarteF commented
I thinks this is ready to merge.

2024-12-10 14:10 UTC, merged